### ISSUE TITLE
Action and Condition can and should be interfaces, so implementation can subclass others

### ISSUE THREAD

**Issue by dongbat** [gaia-ucm/jbt#1]

**Comment by ricardojuanpalmaduran** [comment]
No, they cannot, at least the way the library is designed right now. The abstract base class for mode tasks implements certain functionality (such as storing guards) that must be in all task classes. 

In any case, those classes are meant to be generated by the editor tools automatically, so you should not try to alter them in any way. Note that the BT at a conceptual level (model tasks) is just an empty shell describing in an abstract way what the tree does, but how that is actually done is determined by the execution nodes. Therefore, the model tasks (including actiond and conditions) are useless in practice.
