### ISSUE TITLE
seek complete sample

### ISSUE THREAD

**Issue by yeungeek** [gaia-ucm/jbt#2]
Recently, I'm learning Behavior tree, then discover the project. it's awesome project.
Based on UserGuide, I probably understand JBT Architecture, but lack of sample. Some important points can not be understood thoroughly. Can provide samples?

Thanks
my email yeungeek#gmail.com

**Comment by ricardojuanpalmaduran** [comment]
Hi @yeungeek 

As far as I see the user guide is comprehensive enough to start building BTs without any previous experience. In particular, the guide goes over a real example and all the steps involved in the process. So please, if you could provide specific examples of what parts are not clear I could give you a hand there or maybe complete the documentation.

**Comment by yeungeek** [comment]
Hi @ricardojuanpalmaduran 
According to guide, I use JBTEditor, draw this:
![20140731120103](https://cloud.githubusercontent.com/assets/271539/3759827/5deeb69c-1867-11e4-8bf9-07c22296ada4.png)
It's so cool, does JBTEditor have roadmap, visual? like gamebrainsai

**Comment by ricardojuanpalmaduran** [comment]
There is just the user guide, where the tool is properly explained. Nothing more.

**Comment by yeungeek** [comment]
That's very useful for me to understand BTs, extremely grateful
